
name: 'Project Changelog'

description: 'Creates issue for the corresponding project cards given a column name'

branding:
  icon: "check-square"
  color: "green"

inputs:
  columns:
    description: Project Column names separated by comma
    required: true
  project-beta-number:
    description: Project beta number
    required: true
  organization:
    description: Organization name
    required: true
  template:
    description: Handlebar template to generate markdown
    required: false
    default: "{{title}} {{#if assignees }} by {{assignees}} {{/if}} {{#if number}} in [#{{number}}]({{url}}) {{/if}}"

runs:
  using: 'node16'
  main: 'dist/index.js'
